exports.User  = require('./user')
exports.Img   = require('./img')
exports.ImgRP = require('./imgrp')
exports.TxtRP = require('./txtrp')
exports.Temp  = require('./temp')
exports.Shop  = require('./shop')
exports.Page  = require('./page')
exports.Store = require('./store')
